externalURL: https://example.com/home
timeZone: { name: China, offset: 28800 }
mailer: "mailer://smtp.exmail.qq.com:587/?user=报警<alarm@exmaple.com>&pass=123456"
keepers: [ "小美<xiaomei-go@qq.com>" ]

data:
  postgres:
    test: postgres://postgres:postgres@localhost/postgres?sslmode=disable
    shards:
      1: postgres://postgres:@localhost/test_1?sslmode=disable
      2: postgres://postgres:@localhost/test_2?sslmode=disable
      settings: { idSeqIncrementBy: 1000 }


# 配置中心数据，只有服务端有
configCenter:
  pull: "https://cc-qa.threesoft.cn/config/pull?project=erp&env=qa2&version=1.0&endPointType=server&secret=123&hash="
