postgres:
  test: postgres://postgres:@localhost/test?sslmode=disable
  shards:
    1: postgres://postgres:@localhost/test_1?sslmode=disable
    2: postgres://postgres:@localhost/test_2?sslmode=disable
    settings: { idSeqIncrementBy: 1000 }
